# Generated by Django 4.0.5 on 2022-06-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='query',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='records',
            name='reason',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='records',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
