# Generated by Django 4.0.5 on 2022-06-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_records_query_alter_records_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='time',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
